codecov:
  branch: master

coverage:
  precision: 2
  round: up

  ignore:
    - "src/com/transgressoft/randomfilecopier/RandomFileCopier.java"
    - "src/org/docopt/*"
    - "src/com/transgressoft/commons/util/*"
    - "test/*"
