codecov:
  branch: master

coverage:
  precision: 2
  round: up

  ignore:
      - "src/com/transgressoft/util/*"
      - "src/com/transgressoft/randomfilecopier/RandomFileCopier.java"
      - "src/org/*"
      - "test/*"
